version: "3.8"

services:
  api:
    build:
      context: .
      target: builder
    container_name: battleship-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:./database/app.sqlite
    volumes:
      - .:/usr/app
      - /usr/app/node_modules # Avoid mounting node_modules from the host for SQLite
      - ./database:/usr/app/database
    command: npm run start:dev
